name: First Workflow

on: 
  workflow_dispatch:
  issues: 
    types: [opened]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step One
      run: echo "Step One Log"
    
    - name: Step Two
      run: echo "Step Two Log"  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Cowsays
      uses: mscoutermarsh/cowsays-action@v1
      with:
        text: Vikas, Ship it!!!!!
        color: red
          
